### ISSUE TITLE
0.19

### ISSUE THREAD

**Issue by ronanyeah** [basti1302/elm-non-empty-array#5]
Any plans for 19? If not that's cool, I can fork and have a try myself.

**Comment by basti1302** [comment]
I won't find the time soon to do the update, so if you want to take a stab at it, go ahead, would be much appreciated!

**Comment by devnacho** [comment]
@ronanyeah did you have any success forking it?

@basti1302 Thanks for this library 😄. Do you think updating to 0.19 will be hard?

**Comment by ronanyeah** [comment]
Don't need it urgently at the moment so nothing to report.

**Comment by basti1302** [comment]
@devnacho took care of this in #6
